# Generated by Django 4.2 on 2023-05-04 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('компания', 'Компания'), ('физ.Лицо', 'Физ.Лицо')], default='Физ.лицо', max_length=15, verbose_name='Тип клиента')),
                ('client_name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=40, verbose_name='Номер телефона')),
                ('client_email', models.CharField(max_length=100, verbose_name='Email')),
                ('client_address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('client_found', models.CharField(choices=[('знакомые', 'Знакомые'), ('интернет', 'Интернет'), ('реклама', 'Реклама')], default='Знакомые', max_length=15, verbose_name='Откуда клиент узнал о нас?')),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.CharField(choices=[('устройство', 'Устройство'), ('запчасти', 'Запчасти'), ('товар', 'Товар')], default='устройство', max_length=15, verbose_name='Категория')),
                ('inventory_article', models.IntegerField(verbose_name='Артикул')),
                ('inventory_name', models.CharField(max_length=50, verbose_name='Название')),
                ('inventory_color', models.CharField(max_length=40, verbose_name='Цвет')),
                ('inventory_condition', models.CharField(max_length=100, verbose_name='Состояние')),
                ('inventory_description', models.CharField(max_length=1000, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, verbose_name='Название роли')),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('task_description', models.CharField(max_length=1000, verbose_name='Описание задачи')),
                ('task_time', models.DateTimeField(default=datetime.date.today, verbose_name='Крайний срок')),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_name', models.CharField(max_length=100, verbose_name='Наименование работы')),
                ('sales_comment', models.CharField(max_length=100, verbose_name='Комментарий')),
                ('sales_price', models.CharField(max_length=100, verbose_name='Цена')),
                ('sales_time', models.DateTimeField(default=datetime.date.today, verbose_name='Время продажи')),
                ('sales_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itservice.client')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=50, verbose_name='Название заказа')),
                ('order_description', models.CharField(max_length=1000, verbose_name='Требования к заказу')),
                ('order_time', models.DateField(default=datetime.date.today, verbose_name='Крайний срок')),
                ('order_price', models.IntegerField(verbose_name='Ориентировочная стоимость')),
                ('order_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itservice.client', verbose_name='Клиент')),
            ],
        ),
    ]
