# Generated by Django 4.2 on 2023-05-04 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itservice.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_time',
            field=models.DateField(default=datetime.date.today, verbose_name='Крайний срок'),
        ),
    ]
