# Generated by Django 4.2 on 2023-05-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itservice', '0002_inventory_inventory_client_alter_tasks_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('устройство', 'Устройство'), ('запчасти', 'Запчасти')], default='устройство', max_length=15, verbose_name='Категория'),
        ),
    ]
