# Generated by Django 4.2 on 2023-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itservice', '0002_users_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Техник', 'Техник'), ('Программист', 'Программист'), ('Менеджер', 'Менеджер')], default='Программист', max_length=50, verbose_name='Должность'),
        ),
    ]
