# Generated by Django 4.2 on 2023-05-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itservice', '0003_alter_users_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_fio', models.CharField(max_length=50, verbose_name='Фио')),
                ('application_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('application_email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('application_address', models.CharField(max_length=50, verbose_name='Ваш адрес')),
                ('application_found', models.CharField(choices=[('Знакомые', 'Знакомые'), ('Интернет', 'Интернет'), ('Реклама', 'Реклама')], default='Реклама', max_length=15, verbose_name='Откуда вы узнали о нас?')),
                ('application_comment', models.CharField(max_length=300, verbose_name='Заявка')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_fio', models.CharField(max_length=50, verbose_name='Фио')),
                ('review_gender', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], default='Мужчина', max_length=15, verbose_name='Пол')),
                ('review_email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('review_comment', models.CharField(max_length=50, verbose_name='Отзыв')),
                ('review_answer', models.CharField(max_length=50, null=True, verbose_name='Ответ')),
            ],
        ),
    ]
