# Generated by Django 4.2 on 2023-05-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itservice', '0003_alter_inventory_inventory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
