# Generated by Django 4.2 on 2023-05-04 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itservice', '0004_orders_order_active_tasks_task_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Крайний срок'),
        ),
    ]
