# Generated by Django 4.2 on 2023-05-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itservice', '0004_application_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_answer',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_comment',
            field=models.CharField(max_length=150, verbose_name='Отзыв'),
        ),
    ]
