# Generated by Django 4.2 on 2023-05-04 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itservice', '0005_alter_tasks_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Крайний срок'),
        ),
    ]
